### PR TITLE
Make OAuth tokens accessible

### PR DESCRIPTION
**Pull request by jmnavarro**
Bruno, I need this for credentials storage in OAuth support for Screens

Thanks!

### CODE REVIEW

**Comment by brunofarache** [comment]
Hey José, shouldn't we just make _config accessible? Does it work if I add a getConfig() only?

**Comment by brunofarache** [comment]
Just started reviewing <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by brunofarache** [comment]
Thank you, pull request merged! <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by brunofarache** [comment]
Your change wasn't compiling, missing parenthesis. This is not Swift ;)

**Comment by jmnavarro** [comment]
Ups sorry, that was a mess of code (:

Regarding the getConfig() method instead of getters, I was trying to follow the [Law of Demeter](http://en.wikipedia.org/wiki/Law_of_Demeter) to hide inner structures

**Pull request merged**
